import { DemoScenario } from '../types/speakerFingerprint';

export const DEMO_SCENARIOS: Record<string, DemoScenario> = {
  trusted_caller: {
    id: 'trusted_caller',
    title: 'Scenario 1 — Trusted Caller',
    description: 'Amit calls for casual family catchup. Natural voice match (94%), zero financial risk.',
    contactName: 'Amit',
    relationship: 'Brother',
    expectedOutcome: 'Safe / Low Risk • Background verification green',
    transcriptSteps: [
      {
        delayMs: 1500,
        speaker: 'Amit',
        text: 'Hey! Are you free this weekend for mom’s birthday dinner?',
        similarity: 0.94,
        status: 'match',
        syntheticScore: 0.06,
        domain: 'Family Catchup',
        financial: false,
        urgency: 'NONE',
      },
      {
        delayMs: 4000,
        speaker: 'Amit',
        text: 'I was thinking we can pick up the cake from the bakery nearby around 5 PM.',
        similarity: 0.92,
        status: 'match',
        syntheticScore: 0.05,
        domain: 'Family Catchup',
        financial: false,
        urgency: 'NONE',
      },
      {
        delayMs: 4500,
        speaker: 'Amit',
        text: 'Let me know what time works best for you and I will reserve the table.',
        similarity: 0.95,
        status: 'match',
        syntheticScore: 0.07,
        domain: 'Family Catchup',
        financial: false,
        urgency: 'NONE',
      },
    ],
  },

  different_speaker: {
    id: 'different_speaker',
    title: 'Scenario 2 — Different Speaker / Phone Handover',
    description: 'Amit starts speaking, but then an unknown person takes over the call to demand assistance.',
    contactName: 'Amit',
    relationship: 'Brother',
    expectedOutcome: 'Speaker Change Warning • Mismatch Alert (38%)',
    transcriptSteps: [
      {
        delayMs: 1500,
        speaker: 'Amit',
        text: 'Hey, I’m with a friend right now...',
        similarity: 0.91,
        status: 'match',
        syntheticScore: 0.08,
        speakerChanged: false,
        domain: 'General',
        financial: false,
        urgency: 'NONE',
      },
      {
        delayMs: 3500,
        speaker: 'Unknown Person',
        text: 'Actually, I’ll explain the issue. Amit had an accident and his phone is damaged.',
        similarity: 0.38,
        status: 'possibleMismatch',
        syntheticScore: 0.12,
        speakerChanged: true,
        domain: 'Emergency Appeal',
        financial: false,
        urgency: 'MEDIUM',
      },
      {
        delayMs: 4500,
        speaker: 'Unknown Person',
        text: 'You need to transfer funds right away to the hospital clinic account.',
        similarity: 0.34,
        status: 'unknown',
        syntheticScore: 0.15,
        speakerChanged: true,
        domain: 'Emergency Appeal',
        financial: true,
        urgency: 'HIGH',
        triggerVerification: true,
      },
    ],
  },

  ai_banking_scam: {
    id: 'ai_banking_scam',
    title: 'Scenario 3 — AI Cloned Voice + Banking Scam',
    description: 'Cloned AI voice sounding like Amit urgently requesting ₹50,000 to a new bank account.',
    contactName: 'Amit',
    relationship: 'Brother',
    expectedOutcome: 'Critical Risk • High Synthetic Score (91%) + Verification Question Failure',
    transcriptSteps: [
      {
        delayMs: 1500,
        speaker: 'Amit (Cloned AI)',
        text: 'Hello, listen carefully. I have a huge problem with my bank account.',
        similarity: 0.89,
        status: 'match',
        syntheticScore: 0.88,
        domain: 'Banking & Financial',
        financial: true,
        urgency: 'MEDIUM',
      },
      {
        delayMs: 3800,
        speaker: 'Amit (Cloned AI)',
        text: 'I urgently need ₹50,000 transferred right now or my account will be locked!',
        similarity: 0.88,
        status: 'match',
        syntheticScore: 0.92,
        domain: 'Banking & Financial',
        financial: true,
        urgency: 'HIGH',
        triggerVerification: true,
        simulatedCallerResponse: 'Uhh... we went to McDonald’s last month, hurry up and send the money!',
        simulatedCallerAnswerCorrect: false,
      },
    ],
  },

  real_voice_scam: {
    id: 'real_voice_scam',
    title: 'Scenario 4 — Real Voice + Compromised Financial Coercion',
    description: 'Caller voice is 100% genuine human Amit, but the conversation is a severe scam or coercion.',
    contactName: 'Amit',
    relationship: 'Brother',
    expectedOutcome: 'Demonstrates Swaraksha doesn’t rely only on deepfakes: Risk High due to financial urgency & answer failure',
    transcriptSteps: [
      {
        delayMs: 1500,
        speaker: 'Amit',
        text: 'Hey... please don’t tell anyone, but I am in serious legal trouble with the cyber police.',
        similarity: 0.95,
        status: 'match',
        syntheticScore: 0.05,
        domain: 'Legal / Threat',
        financial: false,
        urgency: 'HIGH',
      },
      {
        delayMs: 3800,
        speaker: 'Amit',
        text: 'They put me on a digital arrest call. Send ₹50,000 to this UPI ID right now or they will raid our house.',
        similarity: 0.94,
        status: 'match',
        syntheticScore: 0.06,
        domain: 'Digital Arrest Scam',
        financial: true,
        urgency: 'HIGH',
        triggerVerification: true,
        simulatedCallerResponse: 'I don’t have time for trivia! Just send the money to the UPI ID!',
        simulatedCallerAnswerCorrect: false,
      },
    ],
  },
};
