# PowerShell build script for Swaraksha Android APK
# Finds or installs Java 17 LTS, clears conflicting Java 25 caches, and builds APK

$ErrorActionPreference = "Stop"

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "  Swaraksha Android APK Builder (Java 17) " -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan

# 1. Kill any existing Gradle / Java daemons
Write-Host "`n[1/5] Stopping stale background daemons..." -ForegroundColor Yellow
Get-Process -Name java -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 1

# 2. Check for Java 17 installations
Write-Host "`n[2/5] Locating Java 17..." -ForegroundColor Yellow
$java17Candidates = @(
    "C:\Program Files\Eclipse Adoptium\jdk-17*",
    "C:\Program Files\Java\jdk-17*",
    "C:\Program Files\Microsoft\jdk-17*",
    "C:\Program Files\BellSoft\LibericaJDK-17*",
    "C:\Program Files\Amazon Corretto\jdk17*"
)

$foundJdk = $null
foreach ($pattern in $java17Candidates) {
    $dirs = Get-Item $pattern -ErrorAction SilentlyContinue
    if ($dirs) {
        $foundJdk = $dirs[0].FullName
        break
    }
}

if (-not $foundJdk) {
    Write-Host "Java 17 is not yet installed on this PC." -ForegroundColor Red
    Write-Host "Installing Eclipse Temurin Java 17 via winget (official, free LTS)..." -ForegroundColor Yellow
    winget install --id EclipseAdoptium.Temurin.17.JDK -e --silent --accept-package-agreements --accept-source-agreements
    
    # Check again after install
    $dirs = Get-Item "C:\Program Files\Eclipse Adoptium\jdk-17*" -ErrorAction SilentlyContinue
    if ($dirs) {
        $foundJdk = $dirs[0].FullName
    }
}

if ($foundJdk) {
    Write-Host " Using Java 17 at: $foundJdk" -ForegroundColor Green
    $env:JAVA_HOME = $foundJdk
    $env:PATH = "$foundJdk\bin;$env:PATH"
    & flutter config --jdk-dir "$foundJdk"
} else {
    Write-Host "⚠ Could not auto-locate Java 17 directory. Please install Temurin 17 from: https://adoptium.net/temurin/releases/?version=17" -ForegroundColor Red
    exit 1
}

# 3. Purge bad bytecode caches generated by Java 25
Write-Host "`n[3/5] Cleaning corrupt Java 25 caches..." -ForegroundColor Yellow
Remove-Item -Recurse -Force "$env:USERPROFILE\.gradle\caches\8.4\scripts" -ErrorAction SilentlyContinue
Remove-Item -Recurse -Force "$env:USERPROFILE\.gradle\caches\8.13" -ErrorAction SilentlyContinue
Remove-Item -Recurse -Force "$env:USERPROFILE\.gradle\wrapper\dists\gradle-8.13*" -ErrorAction SilentlyContinue
Remove-Item -Recurse -Force "$env:USERPROFILE\.gradle\daemon" -ErrorAction SilentlyContinue

# 4. Clean Flutter state
Write-Host "`n[4/5] Running flutter clean & pub get..." -ForegroundColor Yellow
& flutter clean
& flutter pub get

# 5. Build APK
Write-Host "`n[5/5] Building Release APK with Gradle 8.4 on Java 17..." -ForegroundColor Yellow
& flutter build apk --release
if ($LASTEXITCODE -ne 0) {
    Write-Host "`n[ERROR] Flutter build apk failed with exit code $LASTEXITCODE." -ForegroundColor Red
    exit $LASTEXITCODE
}

Write-Host "`n==========================================" -ForegroundColor Green
Write-Host " BUILD SUCCESSFUL! " -ForegroundColor Green
Write-Host " APK location: build\app\outputs\flutter-apk\app-release.apk" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
